### 1D Array in Numpy

In [ ]:
import numpy as np

In [2]:
array = np.array([1, 2, 3, 4, 5])
print("Array:", array)
print(type(array))

Array: [1 2 3 4 5]
<class 'numpy.ndarray'>


### Multi Dimensional Array 

In [3]:
array = np.array("A")
print(array.ndim)  # Output: 0

0


In [4]:
array = np.array(["A", "B", "C"])
print(array.ndim)  # Output: 1

1


In [5]:
array = np.array([["A", "B", "C"], 
                  ["D", "E", "F"], 
                  ["G", "H", "I"]])
print(array.ndim)  # Output: 2
# 2D array, like a matrix
print(array.shape)

2
(3, 3)


In [6]:
array = np.array([[["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"]],
                  [["J", "K", "L"], ["M", "N", "O"], ["P", "Q", "R"]],
                  [["S", "T", "U"], ["V", "W", "X"], ["Y", "Z", "0"]]])
print(array.ndim)  # Output: 3
print(array.shape)  # Output: (3, 3, 3)

3
(3, 3, 3)


In [7]:
# Indexing,
print(array[0, 1, 2])  # Output: F

F


In [8]:
# Creating a word
word = array[0, 0, 0] + array[2, 0, 0] + array[2, 0, 0]
word

'ASS'

### Slicing

In [10]:
array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])
# array[row_start:row_end:step, col_start:col_end:step]
# row_start and col_start is inclusive, row_end and col_end is exclusive
print(array[0:3:2])
print("----")
print(array[::-1]) # prints in reverse order
print("----")
print(array[:, 1])
print("----")
print(array[:, 1:3])

[[ 1  2  3  4]
 [ 9 10 11 12]]
----
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
----
[ 2  6 10 14]
----
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### Arithmetic

In [13]:
# Scalar arithmetic
array = np.array([1, 2, 3])
print(array + 10)
print(array - 10)
print(array * 10)
print(array / 10)
print(array ** 2)

[11 12 13]
[-9 -8 -7]
[10 20 30]
[0.1 0.2 0.3]
[1 4 9]


In [17]:
# Vectorized math functions
array = np.array([1.01, 2.35, 3.99])
print(np.sqrt(array))
print(np.round(array))
print(np.ceil(array))
print(np.floor(array))
print(np.pi) # built-in constant

[1.00498756 1.53297097 1.99749844]
[1. 2. 4.]
[2. 3. 4.]
[1. 2. 3.]
3.141592653589793


In [18]:
## Calculate the area of a circle given the radius
radii = np.array([1, 2, 3, 4, 5])
print(np.pi * (radii ** 2))

[ 3.14159265 12.56637061 28.27433388 50.26548246 78.53981634]


In [23]:
# Element wise operations
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [31]:
# Comparison operations
scores = np.array([55, 90, 30, 92, 88, 100])
print(scores == 100)
print(scores >= 90)
scores[scores < 60] = 0
print(scores)

[False False False False False  True]
[False  True False  True False  True]
[  0  90   0  92  88 100]


### Array Broadcasting
* Array broadcasting in NumPy is a way for arrays with different shapes to be used together in arithmetic operations without explicitly copying or reshaping data.

* In short: NumPy automatically stretches smaller arrays so their shapes are compatible.
* Two dimensions are compatible if:

    - They are equal, or

    - One of them is 1

In [35]:
array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
print(array1.shape)
print(array2.shape)
print(array1 * array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


### Aggregate functions
* It summarizes the data and typically returns a single value

In [45]:
array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8]])
print(np.sum(array))          # Sum of all elements
print(np.sum(array, axis=0))  # Sum of each column
print(np.sum(array, axis=1))  # Sum of each row
print(np.mean(array))         # Mean of all elements
print(np.std(array))          # Standard deviation of all elements
print(np.min(array))          # Minimum element
print(np.max(array))          # Maximum element
print(np.argmin(array))       # Index of minimum element
print(np.argmax(array))       # Index of maximum element

36
[ 6  8 10 12]
[10 26]
4.5
2.29128784747792
1
8
0
7


### Filtering
* It is the process of selecting elements from an array that match a given condition

In [50]:
ages = np.array([[25, 30, 35, 40, 14, 50],
                [15, 17, 39, 28, 50, 22]])
teenagers = ages[ages < 20] # boolean indexing, it flattens the array
adults = ages[(ages >= 20) & (ages <= 35)] # boolean indexing with multiple conditions
evens = ages[ages % 2 == 0] # boolean indexing for even numbers
print(teenagers)
print(adults)
print(evens)

[14 15 17]
[25 30 35 28 22]
[30 40 14 50 28 50 22]


In [51]:
# To retain the shape, use np.where

adults = np.where((ages >= 20) & (ages <= 35), ages, 0)
print(adults)

[[25 30 35  0  0  0]
 [ 0  0  0 28  0 22]]


### Random Numbers

In [56]:
rng = np.random.default_rng()
print(rng.integers(1, 100, size=10))  # 10 random integers between 1 and 100
print(rng.random(size=(3, 4)))  # 3x4 array of random floats between 0 and 1

[32 47 11 37 61 17 83 57 59 46]
[[0.18145731 0.83245728 0.90284958 0.82000067]
 [0.85775349 0.41747011 0.27769258 0.72494772]
 [0.37261227 0.02802644 0.79176614 0.02215247]]


In [58]:
rng = np.random.default_rng()
array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)
print(array)

[5 2 4 1 3]


In [63]:
# Choose random elements from an array
fruits = np.array(["apple", "banana", "cherry", "date", "elderberry"])
rng.choice(fruits, size=3)


array(['cherry', 'elderberry', 'cherry'], dtype='<U10')